#!/bin/bash

echo "const myState = {"

echo "    PORT: \`$PORT\`,"
echo "    LOCAL_API_ROOT: \`$LOCAL_API_ROOT\`,"
echo "    LOCAL_API_TIMEOUT: \`$LOCAL_API_TIMEOUT\`,"
echo "    API_ROOT: \`$API_ROOT\`,"
echo "    LOG_MODE: \`$LOG_MODE\`,"
echo "    GOOGLE_REDIRECT_URL: \`$GOOGLE_REDIRECT_URL\`,"
echo "    GOOGLE_AUTH_URL: \`$GOOGLE_AUTH_URL\`,"
echo "    GOOGLE_CLIENT_ID: \`$GOOGLE_CLIENT_ID\`,"
echo "    FACEBOOK_REDIRECT_URL: \`$FACEBOOK_REDIRECT_URL\`,"
echo "    FACEBOOK_AUTH_URL: \`$FACEBOOK_AUTH_URL\`,"
echo "    FACEBOOK_CLIENT_ID: \`$FACEBOOK_CLIENT_ID\`,"
echo "    FIREBASE_CONFIG: \`$FIREBASE_CONFIG\`,"
echo "    FACEBOOK_CHAT_ID: \`$FACEBOOK_CHAT_ID\`,"
echo "    WORKER_ROOT: \`$WORKER_ROOT\`,"
echo "    UPLOAD_ROOT: \`$UPLOAD_ROOT\`,"
echo "    GA_KEY: \`$GA_KEY\`,"
echo "    PAYMENT_DATE: \`$PAYMENT_DATE\`,"
echo "    REDIRECT_URL: \`$REDIRECT_URL\`,"
echo "    SLIDE_PARTNER: \`$SLIDE_PARTNER\`,"
echo "    GOOGLE_ADS_BLOCK: \`$GOOGLE_ADS_BLOCK\`,"
echo "    DOMAIN_ROOT: \`$DOMAIN_ROOT\`,"
echo "    IS_LANDING: \`$IS_LANDING\`,"
echo "    IS_NEW_STYLE: \`$IS_NEW_STYLE\`,"
echo "    REDIRECT_301: \`$REDIRECT_301\`,"
echo "    API_MAP: \`$API_MAP\`,"
echo "    MAP_ID: \`$MAP_ID\`,"

echo "};"