import React, { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ContentFilterWrap, ContentInnerFilter, ContentInnerSeeMore } from "./styled/ContentStyle";
import { BlogDetailContentInner } from "../blog/styled/blogStyled";
import { LabelData } from "../../../models/Staff";

export default function ContentFilterSpa(props: { labelData?: LabelData }) {
    let { lang,link } = useParams<{ lang: string, link: string }>();
    const [isExpanded, setIsExpanded] = useState(true);
    const provinceName =
        props.labelData?.apartment?.name ||
        props.labelData?.commune?.name ||
        props.labelData?.district?.name ||
        props.labelData?.province?.name ||
        "";
    const contentVi = `<h2 dir=\"ltr\">Dịch vụ massage ${provinceName}</h2>\n<p dir=\"ltr\">H&atilde;y đến một trong những dịch vụ massage ${provinceName} chất lượng cao gần nơi bạn sống, họ sẽ đảm bảo mang đến cho bạn liệu ph&aacute;p thư gi&atilde;n gi&uacute;p bạn qu&ecirc;n đi mọi căng thẳng.</p>\n<p dir=\"ltr\">&nbsp;</p>\n<p dir=\"ltr\">Danh s&aacute;ch tr&ecirc;n bao gồm c&aacute;c dịch vụ massage ${provinceName} h&agrave;ng đầu, Glow ch&uacute; trọng v&agrave;o c&aacute;c liệu ph&aacute;p massage body, massage trị liệu ​​gi&uacute;p chữa l&agrave;nh v&agrave; thư gi&atilde;n cơ thể. Sử dụng c&aacute;c kỹ năng xoa b&oacute;p, bấm huyệt, c&ugrave;ng c&aacute;c dụng cụ như đ&aacute; n&oacute;ng, gi&aacute;c hơi để k&iacute;ch th&iacute;ch c&aacute;c cơ, l&agrave;m cơ thể thư gi&atilde;n v&agrave; vận động tốt hơn. Một buổi aroma massage với tinh dầu thơm cũng sẽ tạo ra sự thư gi&atilde;n ho&agrave;n to&agrave;n cho cơ thể v&agrave; t&acirc;m hồn. Ngo&agrave;i ra, c&aacute;c liệu ph&aacute;p kh&aacute;c như gội đầu dưỡng sinh ${provinceName}, lấy r&aacute;y tai ${provinceName} cũng rất c&oacute; lợi. Lưu &yacute;, Glow kh&ocirc;ng liệt k&ecirc; c&aacute;c dịch vụ như massage nuru ${provinceName}, massage lingam ${provinceName}, massage thư gi&atilde;n từ A đến Z ${provinceName}.</p>\n<h2 dir=\"ltr\">Top 10 địa chỉ Massage ${provinceName}</h2>\n<p dir=\"ltr\">Cuộc sống h&agrave;ng ng&agrave;y c&oacute; thể rất mệt mỏi, đặc biệt l&agrave; ở khu vực đ&ocirc; thị ${provinceName}. Giờ l&agrave;m việc d&agrave;i h&agrave;ng ng&agrave;y v&agrave; đường phố &ocirc; nhiễm do &ugrave;n tắc giao th&ocirc;ng hỗn loạn chắc chắn sẽ g&acirc;y ra căng thẳng. Về l&acirc;u d&agrave;i, c&aacute;c vấn đề về sức khỏe thể chất v&agrave; tinh thần c&oacute; thể xảy ra. May mắn thay, c&oacute; rất nhiều dịch vụ massage ${provinceName}. Bạn đ&atilde; tự hỏi m&igrave;nh n&ecirc;n đến đ&acirc;u để được massage gần t&ocirc;i ${provinceName}? Glow sẽ gi&uacute;p bạn trả lời trong nh&aacute;y mắt.</p>\n<p dir=\"ltr\">&nbsp;</p>\n<p dir=\"ltr\">Th&ocirc;ng qua danh s&aacute;ch tr&ecirc;n, bạn c&oacute; thể dễ d&agrave;ng t&igrave;m thấy top 10 c&aacute;c địa điểm spa v&agrave; massage chất lượng ở ${provinceName}. Ngo&agrave;i ra, khi tải ứng dụng Glow, bạn c&ograve;n c&oacute; thể sắp xếp c&aacute;c địa điểm massage ${provinceName} từ xa tới gần theo đơn vị kil&ocirc;m&eacute;t.</p>\n<h2 dir=\"ltr\">Massage ${provinceName}: voucher, hot deal</h2>\n<p dir=\"ltr\">Với Glow, bạn sẽ t&igrave;m thấy những ưu đ&atilde;i v&agrave; khuyến m&atilde;i massage ${provinceName} tốt nhất, ph&ugrave; hợp với ng&acirc;n s&aacute;ch của m&igrave;nh. Tải ứng dụng tr&ecirc;n Google Play hoặc iOS App Store: <a href=\"https://onelink.to/gsj27p\">https://onelink.to/gsj27p</a>&nbsp;</p>\n<p dir=\"ltr\">&nbsp;</p>`;

    const contentEN = `<h2 dir=\"ltr\">Top 10 Massage ${provinceName}: Services</h2>\n<p dir=\"ltr\">Give yourself a break and take a trip to one of the high quality massage ${provinceName} in your direct neighborhood, they will ensure a relaxing treatment so that you forget the stress that surrounds you.</p>\n<p dir=\"ltr\">&nbsp;</p>\n<p dir=\"ltr\">Above list contains the top 10 Massage ${provinceName} services, we have great emphasis on signature Body Massages, the healing and relaxation of the body. Using physical skills and accessories to stimulate the muscles so that body systems will work better. A good Aromatherapy Massage will generate pure relaxation for body and soul. Beneficial are also new skin care Body Treatments like spa salt, full day onsen, salt cave, hydrotherapy, or natural body scrubs such as tamarind, turmeric and various aromatic oils. Treat yourself with a full body scrub to gently exfoliate the skin and wipe away the stress and impurities to reveal a silky and shiny skin.</p>\n<h2 dir=\"ltr\">Top 10 Massage ${provinceName}: Locations</h2>\n<p dir=\"ltr\">Daily life can be exhausting, especially in a metropolitan area ${provinceName}. Long daily working hours and polluted streets caused by chaotic traffic jams will certainly generate stress. On the long-term issues in physical and mental health can occur. Why not forestall those issues by treating yourself as you deserve it? Luckily you, there are a whole range of spa and massage services ${provinceName}. Have you asked yourself where to go for a massage near me in ${provinceName}? To finally restore your well-being with a full day Spa Package or a Deep Tissue Massage during your lunch break? This just got one step easier.</p>\n<p dir=\"ltr\">&nbsp;</p>\n<p dir=\"ltr\">Through the above list, quality spa and massage salons in ${provinceName} can be found easily. You also find the best massage spa promotions ${provinceName}.&nbsp;</p>\n<h2 dir=\"ltr\">Massage ${provinceName}: Vouchers</h2>\n<p dir=\"ltr\">With Glow you will find the best deals and promotions on massage ${provinceName} that fit your budget. Application on Google Play or iOS App Store: <a href=\"https://onelink.to/gsj27p\">https://onelink.to/gsj27p</a>&nbsp;&nbsp;</p>\n<p dir=\"ltr\">&nbsp;</p>`;

    const contentKR = `<h2 dir=\"ltr\">상위 10개 마사지 서비스 ${provinceName}</h2>\n<p dir=\"ltr\">가까운 고품질 ${provinceName} 마사지 서비스 중 한 곳에 오시면 모든 스트레스를 잊는 데 도움이 되는 편안한 트리트먼트를 보장해 드립니다.</p>\n<p dir=\"ltr\">위 목록에는 상위 10개 ${provinceName} 마사지 서비스가 포함되어 있으며, Glow는 전신 마사지 요법, 몸을 치유하고 이완시키는 데 도움이 되는 치료 마사지에 중점을 둡니다. 마사지 기술, 지압, 핫스톤, 부항 등의 도구를 사용하여 근육을 자극하고 몸을 이완시키며 더 잘 움직일 수 있습니다. 아로마 에센셜 오일을 사용한 아로마 마사지 세션은 몸과 마음의 완벽한 휴식을 선사합니다. 또한 샴푸 및 모발 영양 공급 ${provinceName}, 귀지 제거 ${provinceName} 또는 족욕 및 발 마사지와 같은 편안한 트리트먼트도 매우 유익합니다. 참고로 글로우에는 누루 마사지 ${provinceName}, 링감 마사지 ${provinceName}, A부터 Z까지 릴랙스 마사지 ${provinceName}와 같은 서비스가 나열되어 있지 않습니다.</p>\n<h2 dir=\"ltr\">상위 10개 마사지 주소 ${provinceName}</h2>\n<p dir=\"ltr\">특히 ${provinceName} 도시 지역에서는 일상 생활이 매우 피곤할 수 있습니다. 긴 일일 근무시간과 혼잡한 교통체증으로 인한 오염된 거리는 스트레스의 원인이 될 수밖에 없습니다. 장기적으로는 신체적, 정신적 건강 문제가 발생할 수 있습니다. 다행히 ${provinceName}에는 마사지 서비스가 많이 있습니다. ${provinceName} 근처 마사지 받으러 어디로 가야할지 고민하셨나요? Glow는 신속하게 답변하는 데 도움이 됩니다.</p>\n<p dir=\"ltr\">위 목록을 통해 ${provinceName}의 수준 높은 스파 및 마사지 살롱을 쉽게 찾을 수 있습니다. 또한 Glow 애플리케이션을 다운로드하면 가까운 곳과 먼 곳의 ${provinceName} 마사지 팔러를 킬로미터 단위로 찾을 수도 있습니다.</p>\n<h2 dir=\"ltr\">마사지 ${provinceName}: 이용권, 핫딜</h2>\n<p dir=\"ltr\">Glow를 사용하면 귀하의 예산에 적합한 최고의 ${provinceName} 마사지 제안 및 프로모션을 찾을 수 있습니다. Google Play 또는 iOS App Store에서 애플리케이션을 다운로드하세요: <a href=\"https://onelink.to/gsj27p\">https://onelink.to/gsj27p</a>&nbsp;</p>`;
    const content = lang === "en" ? contentEN : lang === "kr" ? contentKR : contentVi;

    const displayContent = link?.includes("massage") ? content : "";
    return (
        <ContentFilterWrap>
            <ContentInnerFilter
                isExpanded={isExpanded}
                dangerouslySetInnerHTML={{ __html: displayContent || "" }}
            />
        </ContentFilterWrap>
    );
}
